name: branches-master
on:
  push:
    branches:
      - master
      - spike/*
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build:
    needs: tests
    uses: ./.github/workflows/build.yml
